### ISSUE TITLE
Containers in child packages are not recognized

### ISSUE THREAD

**Issue by ptroja** [AdaCore/gnat-gdb-scripts#3] opened 2019-01-08 10:08 UTC
This issue feels similar to #1. However, there the FSF GCC seems to be blamed, while here I am using the AdaCore compiler and debugger (a nightly build from 20181211).

To reproduce, please compile the code with ```gnatmake -g lister```, enter the debugger and print two instances of doubly-linked lists:
```
b lister.adb:10
(gdb) b lister.adb:10
Breakpoint 1 at 0x40d52a: file lister.adb, line 10.
(gdb) r
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /tmp/list/lister 

Breakpoint 1, lister () at lister.adb:10
10	   Foo.Bar.Dummy;
(gdb) p ml
$1 = lister.main_lists.list of length 0
(gdb) step
foo.bar.dummy () at foo-bar.adb:10
10	      L.Append (1);
(gdb) p l
$2 = (first => 0x0, last => 0x0, length => 0, tc => (busy => 0, lock => 0))
```

One of them is pretty-printed as expected (which confirms that my setup is correct), the other is not (which shows that the matcher is not working as it should).

This actually came from debugging the spark2014 toolset; the above is just (hopefully minimal) reproducer.

[list.zip](https://github.com/AdaCore/gnat-gdb-scripts/files/2736206/list.zip)

**Comment by pmderodat** [comment] 2019-01-08 10:20
Hello @ptroja 

Thank you for the reproducer! I can see this on my side as well. Quick investigation reveals that this is due to how GNAT materializes entities nested in package bodies: some suffixes (here Xn) are appended to symbol names. Name matching in `gnatdbg` does not know about these suffixes and thus the pretty-printer for the linked list does not recognize the type.

Anyway, this should be easy to fix.

**Comment by pmderodat** [comment] 2019-01-09 10:20
This is now fixed. Thanks again for reporting this!

**Closed as completed by pmderodat** 2019-01-09 10:20 UTC
